spring:
  profiles:
    active: dev


logging:
  config: classpath:config/logback-spring.xml


---
spring:
  profiles: dev
  datasource:
    url: jdbc:dm://192.168.18.129:5237?genKeyNameCase=0
    username: YJJ
    password: yjj@12345
    driver-class-name: dm.jdbc.driver.DmDriver
mybatis-plus:
  config-location: classpath:config/mybatis_config.xml
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      update-strategy: ignored #默认情况非空数据才进行更新
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0


server:
  max-http-header-size: 500KB
  servlet:
    context-path: /demo
